name: Docker Image CI for GHCR

on:
    push

    
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the Image
              run: | 
                  docker login --username fanisridhar --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                  docker build -t ghcr.io/fanisridhar/arithmetic-service:latest --file Dockerfile .
                  docker push ghcr.io/fanisridhar/arithmetic-service:latest
